// Données pays pour QCountryPicker : liste ISO 3166-1 alpha-2 avec indicatif
// téléphonique et nom en anglais (name) + français (nameFr).
export interface Country {
  /** Code ISO 3166-1 alpha-2 (ex. "FR") */
  code: string
  /** Nom anglais */
  name: string
  /** Nom français (fallback : name) */
  nameFr?: string
  /** Indicatif téléphonique international (ex. "+33") */
  dial: string
}

/** Drapeau emoji d'un code pays ISO (🇫🇷…) — aucun asset requis */
export const flagOf = (code: string): string =>
  code
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)))

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", nameFr: "Afghanistan", dial: "+93" },
  { code: "AL", name: "Albania", nameFr: "Albanie", dial: "+355" },
  { code: "DZ", name: "Algeria", nameFr: "Algérie", dial: "+213" },
  { code: "AS", name: "American Samoa", nameFr: "Samoa américaines", dial: "+1-684" },
  { code: "AD", name: "Andorra", nameFr: "Andorre", dial: "+376" },
  { code: "AO", name: "Angola", nameFr: "Angola", dial: "+244" },
  { code: "AI", name: "Anguilla", nameFr: "Anguilla", dial: "+1-264" },
  { code: "AQ", name: "Antarctica", nameFr: "Antarctique", dial: "+672" },
  { code: "AG", name: "Antigua and Barbuda", nameFr: "Antigua-et-Barbuda", dial: "+1-268" },
  { code: "AR", name: "Argentina", nameFr: "Argentine", dial: "+54" },
  { code: "AM", name: "Armenia", nameFr: "Arménie", dial: "+374" },
  { code: "AW", name: "Aruba", nameFr: "Aruba", dial: "+297" },
  { code: "AU", name: "Australia", nameFr: "Australie", dial: "+61" },
  { code: "AT", name: "Austria", nameFr: "Autriche", dial: "+43" },
  { code: "AZ", name: "Azerbaijan", nameFr: "Azerbaïdjan", dial: "+994" },
  { code: "BS", name: "Bahamas", nameFr: "Bahamas", dial: "+1-242" },
  { code: "BH", name: "Bahrain", nameFr: "Bahreïn", dial: "+973" },
  { code: "BD", name: "Bangladesh", nameFr: "Bangladesh", dial: "+880" },
  { code: "BB", name: "Barbados", nameFr: "Barbade", dial: "+1-246" },
  { code: "BY", name: "Belarus", nameFr: "Biélorussie", dial: "+375" },
  { code: "BE", name: "Belgium", nameFr: "Belgique", dial: "+32" },
  { code: "BZ", name: "Belize", nameFr: "Belize", dial: "+501" },
  { code: "BJ", name: "Benin", nameFr: "Bénin", dial: "+229" },
  { code: "BM", name: "Bermuda", nameFr: "Bermudes", dial: "+1-441" },
  { code: "BT", name: "Bhutan", nameFr: "Bhoutan", dial: "+975" },
  { code: "BO", name: "Bolivia", nameFr: "Bolivie", dial: "+591" },
  { code: "BA", name: "Bosnia and Herzegovina", nameFr: "Bosnie-Herzégovine", dial: "+387" },
  { code: "BW", name: "Botswana", nameFr: "Botswana", dial: "+267" },
  { code: "BV", name: "Bouvet Island", nameFr: "Île Bouvet", dial: "+47" },
  { code: "BR", name: "Brazil", nameFr: "Brésil", dial: "+55" },
  { code: "IO", name: "British Indian Ocean Territory", nameFr: "Territoire britannique de l'océan Indien", dial: "+246" },
  { code: "BN", name: "Brunei Darussalam", nameFr: "Brunei Darussalam", dial: "+673" },
  { code: "BG", name: "Bulgaria", nameFr: "Bulgarie", dial: "+359" },
  { code: "BF", name: "Burkina Faso", nameFr: "Burkina Faso", dial: "+226" },
  { code: "BI", name: "Burundi", nameFr: "Burundi", dial: "+257" },
  { code: "KH", name: "Cambodia", nameFr: "Cambodge", dial: "+855" },
  { code: "CM", name: "Cameroon", nameFr: "Cameroun", dial: "+237" },
  { code: "CA", name: "Canada", nameFr: "Canada", dial: "+1" },
  { code: "CV", name: "Cape Verde", nameFr: "Cap-Vert", dial: "+238" },
  { code: "KY", name: "Cayman Islands", nameFr: "Îles Caïmans", dial: "+1-345" },
  { code: "CF", name: "Central African Republic", nameFr: "République centrafricaine", dial: "+236" },
  { code: "TD", name: "Chad", nameFr: "Tchad", dial: "+235" },
  { code: "CL", name: "Chile", nameFr: "Chili", dial: "+56" },
  { code: "CN", name: "China", nameFr: "Chine", dial: "+86" },
  { code: "CX", name: "Christmas Island", nameFr: "Île Christmas", dial: "+61" },
  { code: "CC", name: "Cocos (Keeling) Islands", nameFr: "Îles Cocos (Keeling)", dial: "+61" },
  { code: "CO", name: "Colombia", nameFr: "Colombie", dial: "+57" },
  { code: "KM", name: "Comoros", nameFr: "Comores", dial: "+269" },
  { code: "CG", name: "Congo", nameFr: "Congo", dial: "+242" },
  { code: "CD", name: "Congo, the Democratic Republic of the", nameFr: "Congo (République démocratique du)", dial: "+243" },
  { code: "CK", name: "Cook Islands", nameFr: "Îles Cook", dial: "+682" },
  { code: "CR", name: "Costa Rica", nameFr: "Costa Rica", dial: "+506" },
  { code: "CI", name: "Côte d'Ivoire", nameFr: "Côte d'Ivoire", dial: "+225" },
  { code: "HR", name: "Croatia", nameFr: "Croatie", dial: "+385" },
  { code: "CU", name: "Cuba", nameFr: "Cuba", dial: "+53" },
  { code: "CY", name: "Cyprus", nameFr: "Chypre", dial: "+357" },
  { code: "CZ", name: "Czech Republic", nameFr: "République tchèque", dial: "+420" },
  { code: "DK", name: "Denmark", nameFr: "Danemark", dial: "+45" },
  { code: "DJ", name: "Djibouti", nameFr: "Djibouti", dial: "+253" },
  { code: "DM", name: "Dominica", nameFr: "Dominique", dial: "+1-767" },
  { code: "DO", name: "Dominican Republic", nameFr: "République dominicaine", dial: "+1-809" },
  { code: "EC", name: "Ecuador", nameFr: "Équateur", dial: "+593" },
  { code: "EG", name: "Egypt", nameFr: "Égypte", dial: "+20" },
  { code: "SV", name: "El Salvador", nameFr: "Salvador", dial: "+503" },
  { code: "GQ", name: "Equatorial Guinea", nameFr: "Guinée équatoriale", dial: "+240" },
  { code: "ER", name: "Eritrea", nameFr: "Érythrée", dial: "+291" },
  { code: "EE", name: "Estonia", nameFr: "Estonie", dial: "+372" },
  { code: "ET", name: "Ethiopia", nameFr: "Éthiopie", dial: "+251" },
  { code: "FK", name: "Falkland Islands (Malvinas)", nameFr: "Îles Malouines (Falkland)", dial: "+500" },
  { code: "FO", name: "Faroe Islands", nameFr: "Îles Féroé", dial: "+298" },
  { code: "FJ", name: "Fiji", nameFr: "Fidji", dial: "+679" },
  { code: "FI", name: "Finland", nameFr: "Finlande", dial: "+358" },
  { code: "FR", name: "France", nameFr: "France", dial: "+33" },
  { code: "GF", name: "French Guiana", nameFr: "Guyane française", dial: "+594" },
  { code: "PF", name: "French Polynesia", nameFr: "Polynésie française", dial: "+689" },
  { code: "TF", name: "French Southern Territories", nameFr: "Terres australes françaises", dial: "+262" },
  { code: "GA", name: "Gabon", nameFr: "Gabon", dial: "+241" },
  { code: "GM", name: "Gambia", nameFr: "Gambie", dial: "+220" },
  { code: "GE", name: "Georgia", nameFr: "Géorgie", dial: "+995" },
  { code: "DE", name: "Germany", nameFr: "Allemagne", dial: "+49" },
  { code: "GH", name: "Ghana", nameFr: "Ghana", dial: "+233" },
  { code: "GI", name: "Gibraltar", nameFr: "Gibraltar", dial: "+350" },
  { code: "GR", name: "Greece", nameFr: "Grèce", dial: "+30" },
  { code: "GL", name: "Greenland", nameFr: "Groenland", dial: "+299" },
  { code: "GD", name: "Grenada", nameFr: "Grenade", dial: "+1-473" },
  { code: "GP", name: "Guadeloupe", nameFr: "Guadeloupe", dial: "+590" },
  { code: "GU", name: "Guam", nameFr: "Guam", dial: "+1-671" },
  { code: "GT", name: "Guatemala", nameFr: "Guatemala", dial: "+502" },
  { code: "GN", name: "Guinea", nameFr: "Guinée", dial: "+224" },
  { code: "GW", name: "Guinea-Bissau", nameFr: "Guinée-Bissau", dial: "+245" },
  { code: "GY", name: "Guyana", nameFr: "Guyana", dial: "+592" },
  { code: "HT", name: "Haiti", nameFr: "Haïti", dial: "+509" },
  { code: "HM", name: "Heard Island and McDonald Islands", nameFr: "Îles Heard-et-MacDonald", dial: "+672" },
  { code: "VA", name: "Holy See (Vatican City State)", nameFr: "Saint-Siège (État de la Cité du Vatican)", dial: "+379" },
  { code: "HN", name: "Honduras", nameFr: "Honduras", dial: "+504" },
  { code: "HK", name: "Hong Kong", nameFr: "Hong Kong", dial: "+852" },
  { code: "HU", name: "Hungary", nameFr: "Hongrie", dial: "+36" },
  { code: "IS", name: "Iceland", nameFr: "Islande", dial: "+354" },
  { code: "IN", name: "India", nameFr: "Inde", dial: "+91" },
  { code: "ID", name: "Indonesia", nameFr: "Indonésie", dial: "+62" },
  { code: "IR", name: "Iran, Islamic Republic of", nameFr: "Iran (République islamique d')", dial: "+98" },
  { code: "IQ", name: "Iraq", nameFr: "Irak", dial: "+964" },
  { code: "IE", name: "Ireland", nameFr: "Irlande", dial: "+353" },
  { code: "IL", name: "Israel", nameFr: "Israël", dial: "+972" },
  { code: "IT", name: "Italy", nameFr: "Italie", dial: "+39" },
  { code: "JM", name: "Jamaica", nameFr: "Jamaïque", dial: "+1-876" },
  { code: "JP", name: "Japan", nameFr: "Japon", dial: "+81" },
  { code: "JO", name: "Jordan", nameFr: "Jordanie", dial: "+962" },
  { code: "KZ", name: "Kazakhstan", nameFr: "Kazakhstan", dial: "+7" },
  { code: "KE", name: "Kenya", nameFr: "Kenya", dial: "+254" },
  { code: "KI", name: "Kiribati", nameFr: "Kiribati", dial: "+686" },
  { code: "KP", name: "Korea, Democratic People's Republic of", nameFr: "Corée (République populaire démocratique de)", dial: "+850" },
  { code: "KR", name: "Korea, Republic of", nameFr: "Corée (République de)", dial: "+82" },
  { code: "KW", name: "Kuwait", nameFr: "Koweït", dial: "+965" },
  { code: "KG", name: "Kyrgyzstan", nameFr: "Kirghizistan", dial: "+996" },
  { code: "LA", name: "Lao People's Democratic Republic", nameFr: "Laos (République démocratique populaire)", dial: "+856" },
  { code: "LV", name: "Latvia", nameFr: "Lettonie", dial: "+371" },
  { code: "LB", name: "Lebanon", nameFr: "Liban", dial: "+961" },
  { code: "LS", name: "Lesotho", nameFr: "Lesotho", dial: "+266" },
  { code: "LR", name: "Liberia", nameFr: "Libéria", dial: "+231" },
  { code: "LY", name: "Libyan Arab Jamahiriya", nameFr: "Jamahiriya arabe libyenne", dial: "+218" },
  { code: "LI", name: "Liechtenstein", nameFr: "Liechtenstein", dial: "+423" },
  { code: "LT", name: "Lithuania", nameFr: "Lituanie", dial: "+370" },
  { code: "LU", name: "Luxembourg", nameFr: "Luxembourg", dial: "+352" },
  { code: "MO", name: "Macao", nameFr: "Macao", dial: "+853" },
  { code: "MK", name: "Macedonia, the Former Yugoslav Republic of", nameFr: "Macédoine (ex-République yougoslave de)", dial: "+389" },
  { code: "MG", name: "Madagascar", nameFr: "Madagascar", dial: "+261" },
  { code: "MW", name: "Malawi", nameFr: "Malawi", dial: "+265" },
  { code: "MY", name: "Malaysia", nameFr: "Malaisie", dial: "+60" },
  { code: "MV", name: "Maldives", nameFr: "Maldives", dial: "+960" },
  { code: "ML", name: "Mali", nameFr: "Mali", dial: "+223" },
  { code: "MT", name: "Malta", nameFr: "Malte", dial: "+356" },
  { code: "MH", name: "Marshall Islands", nameFr: "Îles Marshall", dial: "+692" },
  { code: "MQ", name: "Martinique", nameFr: "Martinique", dial: "+596" },
  { code: "MR", name: "Mauritania", nameFr: "Mauritanie", dial: "+222" },
  { code: "MU", name: "Mauritius", nameFr: "Maurice", dial: "+230" },
  { code: "YT", name: "Mayotte", nameFr: "Mayotte", dial: "+262" },
  { code: "MX", name: "Mexico", nameFr: "Mexique", dial: "+52" },
  { code: "FM", name: "Micronesia, Federated States of", nameFr: "Micronésie (États fédérés de)", dial: "+691" },
  { code: "MD", name: "Moldova, Republic of", nameFr: "Moldavie (République de)", dial: "+373" },
  { code: "MC", name: "Monaco", nameFr: "Monaco", dial: "+377" },
  { code: "MN", name: "Mongolia", nameFr: "Mongolie", dial: "+976" },
  { code: "ME", name: "Montenegro", nameFr: "Monténégro", dial: "+382" },
  { code: "MS", name: "Montserrat", nameFr: "Montserrat", dial: "+1-664" },
  { code: "MA", name: "Morocco", nameFr: "Maroc", dial: "+212" },
  { code: "MZ", name: "Mozambique", nameFr: "Mozambique", dial: "+258" },
  { code: "MM", name: "Myanmar", nameFr: "Myanmar", dial: "+95" },
  { code: "NA", name: "Namibia", nameFr: "Namibie", dial: "+264" },
  { code: "NR", name: "Nauru", nameFr: "Nauru", dial: "+674" },
  { code: "NP", name: "Nepal", nameFr: "Népal", dial: "+977" },
  { code: "NL", name: "Netherlands", nameFr: "Pays-Bas", dial: "+31" },
  { code: "AN", name: "Netherlands Antilles", nameFr: "Antilles néerlandaises", dial: "+599" },
  { code: "NC", name: "New Caledonia", nameFr: "Nouvelle-Calédonie", dial: "+687" },
  { code: "NZ", name: "New Zealand", nameFr: "Nouvelle-Zélande", dial: "+64" },
  { code: "NI", name: "Nicaragua", nameFr: "Nicaragua", dial: "+505" },
  { code: "NE", name: "Niger", nameFr: "Niger", dial: "+227" },
  { code: "NG", name: "Nigeria", nameFr: "Nigéria", dial: "+234" },
  { code: "NU", name: "Niue", nameFr: "Niue", dial: "+683" },
  { code: "NF", name: "Norfolk Island", nameFr: "Île Norfolk", dial: "+672" },
  { code: "MP", name: "Northern Mariana Islands", nameFr: "Îles Mariannes du Nord", dial: "+1-670" },
  { code: "NO", name: "Norway", nameFr: "Norvège", dial: "+47" },
  { code: "OM", name: "Oman", nameFr: "Oman", dial: "+968" },
  { code: "PK", name: "Pakistan", nameFr: "Pakistan", dial: "+92" },
  { code: "PW", name: "Palau", nameFr: "Palaos", dial: "+680" },
  { code: "PS", name: "Palestinian Territory, Occupied", nameFr: "Territoire palestinien (occupé)", dial: "+970" },
  { code: "PA", name: "Panama", nameFr: "Panama", dial: "+507" },
  { code: "PG", name: "Papua New Guinea", nameFr: "Papouasie-Nouvelle-Guinée", dial: "+675" },
  { code: "PY", name: "Paraguay", nameFr: "Paraguay", dial: "+595" },
  { code: "PE", name: "Peru", nameFr: "Pérou", dial: "+51" },
  { code: "PH", name: "Philippines", nameFr: "Philippines", dial: "+63" },
  { code: "PN", name: "Pitcairn", nameFr: "Pitcairn", dial: "+64" },
  { code: "PL", name: "Poland", nameFr: "Pologne", dial: "+48" },
  { code: "PT", name: "Portugal", nameFr: "Portugal", dial: "+351" },
  { code: "PR", name: "Puerto Rico", nameFr: "Porto Rico", dial: "+1-787" },
  { code: "QA", name: "Qatar", nameFr: "Qatar", dial: "+974" },
  { code: "RE", name: "Réunion", nameFr: "Réunion", dial: "+262" },
  { code: "RO", name: "Romania", nameFr: "Roumanie", dial: "+40" },
  { code: "RU", name: "Russian Federation", nameFr: "Russie (Fédération de)", dial: "+7" },
  { code: "RW", name: "Rwanda", nameFr: "Rwanda", dial: "+250" },
  { code: "SH", name: "Saint Helena", nameFr: "Sainte-Hélène", dial: "+290" },
  { code: "KN", name: "Saint Kitts and Nevis", nameFr: "Saint-Kitts-et-Nevis", dial: "+1-869" },
  { code: "LC", name: "Saint Lucia", nameFr: "Sainte-Lucie", dial: "+1-758" },
  { code: "PM", name: "Saint Pierre and Miquelon", nameFr: "Saint-Pierre-et-Miquelon", dial: "+508" },
  { code: "VC", name: "Saint Vincent and the Grenadines", nameFr: "Saint-Vincent-et-les-Grenadines", dial: "+1-784" },
  { code: "WS", name: "Samoa", nameFr: "Samoa", dial: "+685" },
  { code: "SM", name: "San Marino", nameFr: "Saint-Marin", dial: "+378" },
  { code: "ST", name: "Sao Tome and Principe", nameFr: "Sao Tomé-et-Principe", dial: "+239" },
  { code: "SA", name: "Saudi Arabia", nameFr: "Arabie saoudite", dial: "+966" },
  { code: "SN", name: "Senegal", nameFr: "Sénégal", dial: "+221" },
  { code: "RS", name: "Serbia", nameFr: "Serbie", dial: "+381" },
  { code: "SC", name: "Seychelles", nameFr: "Seychelles", dial: "+248" },
  { code: "SL", name: "Sierra Leone", nameFr: "Sierra Leone", dial: "+232" },
  { code: "SG", name: "Singapore", nameFr: "Singapour", dial: "+65" },
  { code: "SK", name: "Slovakia", nameFr: "Slovaquie", dial: "+421" },
  { code: "SI", name: "Slovenia", nameFr: "Slovénie", dial: "+386" },
  { code: "SB", name: "Solomon Islands", nameFr: "Îles Salomon", dial: "+677" },
  { code: "SO", name: "Somalia", nameFr: "Somalie", dial: "+252" },
  { code: "ZA", name: "South Africa", nameFr: "Afrique du Sud", dial: "+27" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", nameFr: "Géorgie du Sud et les Îles Sandwich du Sud", dial: "+500" },
  { code: "ES", name: "Spain", nameFr: "Espagne", dial: "+34" },
  { code: "LK", name: "Sri Lanka", nameFr: "Sri Lanka", dial: "+94" },
  { code: "SD", name: "Sudan", nameFr: "Soudan", dial: "+249" },
  { code: "SR", name: "Suriname", nameFr: "Suriname", dial: "+597" },
  { code: "SJ", name: "Svalbard and Jan Mayen", nameFr: "Svalbard et Jan Mayen", dial: "+47" },
  { code: "SZ", name: "Swaziland", nameFr: "Swaziland", dial: "+268" },
  { code: "SE", name: "Sweden", nameFr: "Suède", dial: "+46" },
  { code: "CH", name: "Switzerland", nameFr: "Suisse", dial: "+41" },
  { code: "SY", name: "Syrian Arab Republic", nameFr: "République arabe syrienne", dial: "+963" },
  { code: "TW", name: "Taiwan, Province of China", nameFr: "Taïwan (Province de Chine)", dial: "+886" },
  { code: "TJ", name: "Tajikistan", nameFr: "Tadjikistan", dial: "+992" },
  { code: "TZ", name: "Tanzania, United Republic of", nameFr: "Tanzanie (République-Unie de)", dial: "+255" },
  { code: "TH", name: "Thailand", nameFr: "Thaïlande", dial: "+66" },
  { code: "TL", name: "Timor-Leste", nameFr: "Timor-Leste", dial: "+670" },
  { code: "TG", name: "Togo", nameFr: "Togo", dial: "+228" },
  { code: "TK", name: "Tokelau", nameFr: "Tokelau", dial: "+690" },
  { code: "TO", name: "Tonga", nameFr: "Tonga", dial: "+676" },
  { code: "TT", name: "Trinidad and Tobago", nameFr: "Trinité-et-Tobago", dial: "+1-868" },
  { code: "TN", name: "Tunisia", nameFr: "Tunisie", dial: "+216" },
  { code: "TR", name: "Turkey", nameFr: "Turquie", dial: "+90" },
  { code: "TM", name: "Turkmenistan", nameFr: "Turkménistan", dial: "+993" },
  { code: "TC", name: "Turks and Caicos Islands", nameFr: "Îles Turques-et-Caïques", dial: "+1-649" },
  { code: "TV", name: "Tuvalu", nameFr: "Tuvalu", dial: "+688" },
  { code: "UG", name: "Uganda", nameFr: "Ouganda", dial: "+256" },
  { code: "UA", name: "Ukraine", nameFr: "Ukraine", dial: "+380" },
  { code: "AE", name: "United Arab Emirates", nameFr: "Émirats arabes unis", dial: "+971" },
  { code: "GB", name: "United Kingdom", nameFr: "Royaume-Uni", dial: "+44" },
  { code: "US", name: "United States", nameFr: "États-Unis", dial: "+1" },
  { code: "UM", name: "United States Minor Outlying Islands", nameFr: "Îles mineures éloignées des États-Unis", dial: "+1" },
  { code: "UY", name: "Uruguay", nameFr: "Uruguay", dial: "+598" },
  { code: "UZ", name: "Uzbekistan", nameFr: "Ouzbékistan", dial: "+998" },
  { code: "VU", name: "Vanuatu", nameFr: "Vanuatu", dial: "+678" },
  { code: "VE", name: "Venezuela", nameFr: "Venezuela", dial: "+58" },
  { code: "VN", name: "Viet Nam", nameFr: "Viet Nam", dial: "+84" },
  { code: "VG", name: "Virgin Islands, British", nameFr: "Îles Vierges britanniques", dial: "+1-284" },
  { code: "VI", name: "Virgin Islands, U.S.", nameFr: "Îles Vierges des États-Unis", dial: "+1-340" },
  { code: "WF", name: "Wallis and Futuna", nameFr: "Wallis-et-Futuna", dial: "+681" },
  { code: "EH", name: "Western Sahara", nameFr: "Sahara occidental", dial: "+212" },
  { code: "YE", name: "Yemen", nameFr: "Yémen", dial: "+967" },
  { code: "ZM", name: "Zambia", nameFr: "Zambie", dial: "+260" },
  { code: "ZW", name: "Zimbabwe", nameFr: "Zimbabwe", dial: "+263" },
]
