// Icônes par défaut du design system — noms Iconify (famille lucide:),
// rendus par le composant <Icon> de @iconify/vue (https://iconify.design/docs/icon-components/vue/).
// Source unique des icônes internes : un composant peut exposer une prop
// d'icône publique (string) qui surcharge ces défauts.
export const icons = {
  arrowDown: "lucide:arrow-down",
  arrowUp: "lucide:arrow-up",
  arrowUpDown: "lucide:arrow-up-down",
  calendarDays: "lucide:calendar-days",
  check: "lucide:check",
  chevronDown: "lucide:chevron-down",
  chevronLeft: "lucide:chevron-left",
  chevronRight: "lucide:chevron-right",
  chevronUp: "lucide:chevron-up",
  chevronsLeft: "lucide:chevrons-left",
  chevronsRight: "lucide:chevrons-right",
  ellipsis: "lucide:ellipsis",
  ellipsisVertical: "lucide:ellipsis-vertical",
  copy: "lucide:copy",
  eye: "lucide:eye",
  eyeOff: "lucide:eye-off",
  file: "lucide:file",
  fileArchive: "lucide:file-archive",
  fileAudio: "lucide:file-audio",
  fileCode: "lucide:file-code",
  fileImage: "lucide:file-image",
  filePlus: "lucide:file-plus",
  fileSpreadsheet: "lucide:file-spreadsheet",
  fileText: "lucide:file-text",
  fileVideo: "lucide:file-video",
  gripVertical: "lucide:grip-vertical",
  imagePlus: "lucide:image-plus",
  menu: "lucide:menu",
  minus: "lucide:minus",
  plus: "lucide:plus",
  refreshCw: "lucide:refresh-cw",
  search: "lucide:search",
  star: "lucide:star",
  x: "lucide:x",
  // — clavier numérique —
  backspace: "lucide:delete",
  // — formatage / édition de cellule (tableur) —
  undo2: "lucide:undo-2",
  redo2: "lucide:redo-2",
  bold: "lucide:bold",
  italic: "lucide:italic",
  eraser: "lucide:eraser",
  alignLeft: "lucide:align-left",
  // — tableur (QSpreadsheet) —
  trash2: "lucide:trash-2",
  clipboardPaste: "lucide:clipboard-paste",
  rows3: "lucide:rows-3",
  columns3: "lucide:columns-3",
  arrowAZ: "lucide:arrow-up-a-z",
  arrowZA: "lucide:arrow-down-a-z",
  squarePlus: "lucide:square-plus",
  squareMinus: "lucide:square-minus",
  pencil: "lucide:pencil",
  sortAsc: "lucide:arrow-up-narrow-wide",
  sortDesc: "lucide:arrow-down-wide-narrow",
  selectCheck: "lucide:check",
  filter: "lucide:filter",
  scissors: "lucide:scissors",
  highlighter: "lucide:highlighter",
  tableCellsMerge: "lucide:table-cells-merge",
} as const
