// Icônes par défaut du design system — noms Iconify (famille lucide:),
// rendus par le composant <Icon> de @iconify/vue (https://iconify.design/docs/icon-components/vue/).
// Source unique des icônes internes : un composant peut exposer une prop
// d'icône publique (string) qui surcharge ces défauts.
export const icons = {
  arrowDown: "lucide:arrow-down",
  arrowUp: "lucide:arrow-up",
  arrowUpDown: "lucide:arrow-up-down",
  calendarDays: "lucide:calendar-days",
  check: "lucide:check",
  chevronDown: "lucide:chevron-down",
  chevronLeft: "lucide:chevron-left",
  chevronRight: "lucide:chevron-right",
  chevronUp: "lucide:chevron-up",
  chevronsLeft: "lucide:chevrons-left",
  chevronsRight: "lucide:chevrons-right",
  copy: "lucide:copy",
  eye: "lucide:eye",
  eyeOff: "lucide:eye-off",
  file: "lucide:file",
  fileArchive: "lucide:file-archive",
  fileAudio: "lucide:file-audio",
  fileCode: "lucide:file-code",
  fileImage: "lucide:file-image",
  filePlus: "lucide:file-plus",
  fileSpreadsheet: "lucide:file-spreadsheet",
  fileText: "lucide:file-text",
  fileVideo: "lucide:file-video",
  gripVertical: "lucide:grip-vertical",
  imagePlus: "lucide:image-plus",
  menu: "lucide:menu",
  minus: "lucide:minus",
  plus: "lucide:plus",
  refreshCw: "lucide:refresh-cw",
  search: "lucide:search",
  star: "lucide:star",
  x: "lucide:x",
} as const
