/**
 * Generates one documentation page per DanxUI component family in content/03-components/.
 * Usage: bun docs/scripts/generate-components-docs.ts
 *
 * - One page per family: e.g. "Accordion" page includes AccordionContent, AccordionItem,
 *   AccordionTrigger — all APIs listed in `componentApi.components`
 * - English description per component (curated map, no source-comment leakage)
 * - Live example (prose-show-case) for stateless components, code block otherwise
 * - The API section (props/slots/events) is auto-generated by Docd (nuxt-component-meta)
 * - Writes .navigation.yml (Nuxt Content v3) for the group title/icon
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises"
import { join } from "node:path"

const ROOT = join(import.meta.dir, "../..")
const COMPONENTS_DIR = join(ROOT, "packages/ui/components")
const OUT_DIR = join(ROOT, "docs/content/03-components")

/** Familles : page principale (sans Q) → composants Q qui la composent. */
const GROUPS: Record<string, string[]> = {
  Accordion: ["QAccordion", "QAccordionContent", "QAccordionItem", "QAccordionTrigger"],
  BottomSheet: ["QBottomSheet", "QBottomSheetHeader", "QBottomSheetFooter", "QBottomSheetTrigger"],
  Bubble: ["QBubble", "QBubbleContent", "QBubbleGroup", "QBubbleReactions"],
  Carousel: ["QCarousel", "QCarouselContent", "QCarouselItem", "QCarouselNav"],
  Card: ["QCard", "QCardContent", "QCardActions"],
  Dialog: ["QDialog", "QDialogHeader", "QDialogFooter", "QDialogTrigger"],
  Fab: ["QFab", "QFabAction"],
  Item: ["QItem", "QItemSection"],
  MessageScroller: [
    "QMessageScroller",
    "QMessageScrollerButton",
    "QMessageScrollerContent",
    "QMessageScrollerItem",
    "QMessageScrollerProvider",
    "QMessageScrollerViewport",
  ],
  NavMenu: ["QNavMenu", "QNavMenuContent", "QNavMenuItem", "QNavMenuTrigger"],
  Sidebar: [
    "QSidebar",
    "QSidebarContent",
    "QSidebarFooter",
    "QSidebarHeader",
    "QSidebarMenu",
    "QSidebarMenuButton",
    "QSidebarMenuItem",
    "QSidebarTrigger",
  ],
  Tabs: ["QTabs", "QTab"],
}

/** Exemples de composition (code blocks — les familles nécessitent un état v-model). */
const GROUP_EXAMPLES: Record<string, Record<string, string>> = {
  Accordion: {
    QAccordion: `<q-accordion v-model="open" type="single" collapsible>
  <q-accordion-item value="intro">
    <q-accordion-trigger>Introduction</q-accordion-trigger>
    <q-accordion-content>
      <p>Section content, collapsible with animation.</p>
    </q-accordion-content>
  </q-accordion-item>
  <q-accordion-item value="api">
    <q-accordion-trigger>API</q-accordion-trigger>
    <q-accordion-content>
      <p>API section below.</p>
    </q-accordion-content>
  </q-accordion-item>
</q-accordion>`,
    QAccordionContent: `<q-accordion-content>Animated item content</q-accordion-content>`,
    QAccordionItem: `<q-accordion-item value="intro">
  <q-accordion-trigger>Title</q-accordion-trigger>
  <q-accordion-content>Content</q-accordion-content>
</q-accordion-item>`,
    QAccordionTrigger: `<q-accordion-trigger>Section title</q-accordion-trigger>`,
  },
  BottomSheet: {
    QBottomSheet: `<q-bottom-sheet v-model="open">
  <template #trigger>
    <q-btn label="Open" />
  </template>
  <q-bottom-sheet-header title="Choose an action" description="Drag the handle down to close." />
  <q-card-content>
    <p>Panel content.</p>
  </q-card-content>
  <q-bottom-sheet-footer>
    <q-btn flat label="Close" @click="open = false" />
  </q-bottom-sheet-footer>
</q-bottom-sheet>`,
    QBottomSheetHeader: `<q-bottom-sheet-header title="Title" description="Description" />`,
    QBottomSheetFooter: `<q-bottom-sheet-footer>
  <q-btn color="primary" label="Confirm" />
</q-bottom-sheet-footer>`,
    QBottomSheetTrigger: `<q-bottom-sheet-trigger>
  <q-btn label="Open the panel" />
</q-bottom-sheet-trigger>`,
  },
  Bubble: {
    QBubble: `<q-bubble-group>
  <q-bubble align="start" variant="muted">
    <q-bubble-content>Hello, how are you?</q-bubble-content>
  </q-bubble>
  <q-bubble align="end" variant="default">
    <q-bubble-content>Very well, thanks!</q-bubble-content>
    <q-bubble-reactions>👍 2</q-bubble-reactions>
  </q-bubble>
</q-bubble-group>`,
    QBubbleContent: `<q-bubble-content>Bubble text</q-bubble-content>`,
    QBubbleGroup: `<q-bubble-group>
  <q-bubble>Message 1</q-bubble>
  <q-bubble>Message 2</q-bubble>
</q-bubble-group>`,
    QBubbleReactions: `<q-bubble-reactions>👍 3 · ❤️ 1</q-bubble-reactions>`,
  },
  Carousel: {
    QCarousel: `<q-carousel :opts="{ loop: true }">
  <q-carousel-content>
    <q-carousel-item class="basis-1/2">Slide 1</q-carousel-item>
    <q-carousel-item class="basis-1/2">Slide 2</q-carousel-item>
    <q-carousel-item class="basis-1/2">Slide 3</q-carousel-item>
  </q-carousel-content>
  <q-carousel-nav />
</q-carousel>`,
    QCarouselContent: `<q-carousel-content>
  <q-carousel-item>Slide 1</q-carousel-item>
</q-carousel-content>`,
    QCarouselItem: `<q-carousel-item>Slide</q-carousel-item>`,
    QCarouselNav: `<q-carousel-nav />`,
  },
  Card: {
    QCard: `<q-card elevated radius="md">
  <q-card-content>
    <p>Card content.</p>
  </q-card-content>
  <q-card-actions align="right">
    <q-btn flat label="Cancel" />
    <q-btn color="primary" label="OK" />
  </q-card-actions>
</q-card>`,
    QCardContent: `<q-card-content>Content block</q-card-content>`,
    QCardActions: `<q-card-actions align="right">
  <q-btn flat label="Cancel" />
  <q-btn color="primary" label="OK" />
</q-card-actions>`,
  },
  Dialog: {
    QDialog: `<q-dialog v-model="open" transition="zoom">
  <q-dialog-header title="Title" description="Dialog description." />
  <q-card-content>
    <p>Modal content.</p>
  </q-card-content>
  <q-dialog-footer>
    <q-btn flat label="Cancel" @click="open = false" />
    <q-btn color="primary" label="OK" @click="open = false" />
  </q-dialog-footer>
</q-dialog>`,
    QDialogHeader: `<q-dialog-header title="Title" description="Description" />`,
    QDialogFooter: `<q-dialog-footer>
  <q-btn color="primary" label="Confirm" />
</q-dialog-footer>`,
    QDialogTrigger: `<q-dialog-trigger>
  <q-btn label="Open" />
</q-dialog-trigger>`,
  },
  Fab: {
    QFab: `<q-fab v-model="open" color="primary" position="bottom-right">
  <q-fab-action label="New" />
  <q-fab-action label="Edit" />
</q-fab>`,
    QFabAction: `<q-fab-action label="New" />`,
  },
  Item: {
    QItem: `<q-list>
  <q-item clickable>
    <q-item-section avatar>
      <q-avatar color="primary" text-color="white">A</q-avatar>
    </q-item-section>
    <q-item-section>Title</q-item-section>
    <q-item-section side>12:00</q-item-section>
  </q-item>
</q-list>`,
    QItemSection: `<q-item-section avatar>…</q-item-section>
<q-item-section>Main content</q-item-section>
<q-item-section side>Meta</q-item-section>`,
  },
  MessageScroller: {
    QMessageScroller: `<q-message-scroller-provider auto-scroll>
  <q-message-scroller class="h-[400px]">
    <q-message-scroller-viewport>
      <q-message-scroller-content>
        <q-message-scroller-item v-for="m in messages" :key="m.id" :message-id="m.id">
          <q-bubble :align="m.from === me ? 'end' : 'start'">{{ m.body }}</q-bubble>
        </q-message-scroller-item>
      </q-message-scroller-content>
    </q-message-scroller-viewport>
    <q-message-scroller-button direction="end" />
  </q-message-scroller>
</q-message-scroller-provider>`,
    QMessageScrollerButton: `<q-message-scroller-button direction="end" />`,
    QMessageScrollerContent: `<q-message-scroller-content>
  <q-message-scroller-item :message-id="m.id">…</q-message-scroller-item>
</q-message-scroller-content>`,
    QMessageScrollerItem: `<q-message-scroller-item :message-id="m.id">
  <q-bubble>Message</q-bubble>
</q-message-scroller-item>`,
    QMessageScrollerProvider: `<q-message-scroller-provider auto-scroll>
  <!-- scroller content -->
</q-message-scroller-provider>`,
    QMessageScrollerViewport: `<q-message-scroller-viewport>
  <q-message-scroller-content>…</q-message-scroller-content>
</q-message-scroller-viewport>`,
  },
  NavMenu: {
    QNavMenu: `<q-nav-menu>
  <q-nav-menu-item href="/docs">
    <q-nav-menu-trigger>Documentation</q-nav-menu-trigger>
    <q-nav-menu-content>
      <q-nav-menu-item href="/docs/getting-started">Getting started</q-nav-menu-item>
    </q-nav-menu-content>
  </q-nav-menu-item>
</q-nav-menu>`,
    QNavMenuContent: `<q-nav-menu-content>
  <q-nav-menu-item href="/docs">Sub link</q-nav-menu-item>
</q-nav-menu-content>`,
    QNavMenuItem: `<q-nav-menu-item href="/docs">Link</q-nav-menu-item>`,
    QNavMenuTrigger: `<q-nav-menu-trigger>Menu</q-nav-menu-trigger>`,
  },
  Sidebar: {
    QSidebar: `<q-sidebar v-model="open" side="left">
  <q-sidebar-header>
    <span class="font-semibold">My app</span>
  </q-sidebar-header>
  <q-sidebar-content>
    <q-sidebar-menu>
      <q-sidebar-menu-item>
        <q-sidebar-menu-button>Home</q-sidebar-menu-button>
      </q-sidebar-menu-item>
      <q-sidebar-menu-item>
        <q-sidebar-menu-button>Settings</q-sidebar-menu-button>
      </q-sidebar-menu-item>
    </q-sidebar-menu>
  </q-sidebar-content>
  <q-sidebar-footer>
    <span class="text-sm">Profile</span>
  </q-sidebar-footer>
</q-sidebar>`,
    QSidebarContent: `<q-sidebar-content>
  <q-sidebar-menu>…</q-sidebar-menu>
</q-sidebar-content>`,
    QSidebarFooter: `<q-sidebar-footer>Bottom area</q-sidebar-footer>`,
    QSidebarHeader: `<q-sidebar-header>Top area</q-sidebar-header>`,
    QSidebarMenu: `<q-sidebar-menu>
  <q-sidebar-menu-item>
    <q-sidebar-menu-button>Item</q-sidebar-menu-button>
  </q-sidebar-menu-item>
</q-sidebar-menu>`,
    QSidebarMenuButton: `<q-sidebar-menu-button>Home</q-sidebar-menu-button>`,
    QSidebarMenuItem: `<q-sidebar-menu-item>
  <q-sidebar-menu-button>Item</q-sidebar-menu-button>
</q-sidebar-menu-item>`,
    QSidebarTrigger: `<q-sidebar-trigger />`,
  },
  Tabs: {
    QTabs: `<q-tabs v-model="tab" align="justify" active-color="secondary">
  <q-tab name="a" label="Tab A" />
  <q-tab name="b" label="Tab B" />
  <q-tab name="c" label="Tab C" />
</q-tabs>`,
    QTab: `<q-tab name="a" label="Tab A" />`,
  },
}

/** Per-component icons. */
const ICONS: Record<string, string> = {
  QBtn: "lucide:mouse-pointer-click",
  QBtnGroup: "lucide:group",
  QInput: "lucide:type",
  QInputPassword: "lucide:key-round",
  QSelect: "lucide:chevrons-up-down",
  QAutocomplete: "lucide:search",
  QCheckbox: "lucide:square-check",
  QRadio: "lucide:circle-dot",
  QSlider: "lucide:sliders-horizontal",
  QRating: "lucide:star",
  QDatePicker: "lucide:calendar",
  QImagePicker: "lucide:image-plus",
  QFilePicker: "lucide:file-plus",
  QDialog: "lucide:square-dashed-mouse-pointer",
  QBottomSheet: "lucide:panel-bottom",
  QActionSheet: "lucide:list",
  QTooltip: "lucide:info",
  QCard: "lucide:credit-card",
  QTable: "lucide:table-2",
  QAvatar: "lucide:user-round",
  QBadge: "lucide:badge-check",
  QChip: "lucide:tags",
  QHeader: "lucide:panel-top",
  QFooter: "lucide:panel-bottom",
  QPage: "lucide:file-text",
  QApp: "lucide:app-window",
  QSidebar: "lucide:panel-left",
  QFab: "lucide:plus",
  QTabs: "lucide:square-dashed-bottom-code",
  QAccordion: "lucide:chevrons-down-up",
  QCollapse: "lucide:chevron-down",
  QCarousel: "lucide:images",
  QPagination: "lucide:chevrons-left-right",
  QNavMenu: "lucide:menu",
  QBubble: "lucide:message-circle",
  QMessageScroller: "lucide:messages-square",
  QConfigProvider: "lucide:palette",
  QIcon: "lucide:sparkles",
  QImg: "lucide:image",
  QSkeleton: "lucide:scan-line",
  QLinearProgress: "lucide:chart-no-axes-column-increasing",
  QCircularProgress: "lucide:loader-circle",
  QInnerLoading: "lucide:loader",
  QToolbar: "lucide:rectangle-horizontal",
  QContainer: "lucide:container",
  QSplitter: "lucide:columns-2",
  QScrollArea: "lucide:scroll",
  QVirtualScroll: "lucide:list-checks",
  QList: "lucide:list",
  QItem: "lucide:rows-3",
  QSeparator: "lucide:minus",
  QText: "lucide:text-quote",
  QSafeArea: "lucide:smartphone",
  QBackHeader: "lucide:arrow-left",
  QPullToRefresh: "lucide:refresh-cw",
  QSpace: "lucide:space",
}

/** English descriptions — one per component (all 91). */
const DESCRIPTIONS: Record<string, string> = {
  // forms
  QBtn: "Button — flat, outline, unelevated variants, sizes, colors, radius.",
  QBtnGroup: "Group of joined buttons sharing a common border.",
  QInput: "Text field — outlined, filled, borderless, clearable, counter, error.",
  QInputPassword: "Password field with a show/hide toggle (eye).",
  QSelect: "Single or multiple selection — client (fuse.js) or server search, chips, inline/modal/sheet/dialog modes.",
  QAutocomplete: "Combobox with client or server filtering (@filter).",
  QCheckbox: "Checkbox — custom values, icons, indeterminate.",
  QRadio: "Radio button — grouped by val/name.",
  QSlider: "Slider — min/max/step, label, markers, vertical.",
  QRating: "Star rating.",
  QDatePicker: "Date picker — inline, sheet, modal, dialog modes.",
  QImagePicker: "Image picker with grid preview, validation (size, count).",
  QFilePicker: "File picker — thumbnail for images, typed icon otherwise.",
  // feedback
  QDialog: "Modal — positions, transitions, maximized, persistent.",
  QDialogHeader: "Modal header — title, description, close button.",
  QDialogFooter: "Modal footer — action area.",
  QDialogTrigger: "Modal opening trigger (alternative to v-model).",
  QBottomSheet: "iOS-style bottom panel — drag to close, safe areas.",
  QBottomSheetHeader: "Bottom sheet header — title, description, close button.",
  QBottomSheetFooter: "Bottom sheet footer — action area.",
  QBottomSheetTrigger: "Bottom sheet opening trigger.",
  QActionSheet: "iOS-style action list.",
  QTooltip: "Tooltip on hover / keyboard focus.",
  QInnerLoading: "Loading overlay inside a container.",
  QLinearProgress: "Linear progress bar — stripe, indeterminate.",
  QCircularProgress: "Circular progress ring — show-value, indeterminate.",
  QPullToRefresh: "Pull-to-refresh gesture.",
  // data display
  QCard: "Card container — elevated, bordered, dark, radius.",
  QCardContent: "Card content block — padding, alignment.",
  QCardActions: "Card actions row — alignment, vertical.",
  QTable: "Data table — sorting, pagination, selection, custom columns.",
  QAvatar: "Avatar — image, icon or initials.",
  QBadge: "Badge / counter / status label.",
  QChip: "Chip — removable, outline, colors.",
  QImg: "Image with ratio, contain/cover, loading and error states.",
  QItem: "List row — clickable, active.",
  QItemSection: "List item section — avatar, side, no-wrap.",
  QList: "List — bordered, separator, dense.",
  QSeparator: "Divider — horizontal/vertical, inset, spaced.",
  QSkeleton: "Loading placeholder — QBtn, QInput, QAvatar types…",
  QText: "Text with multi-line truncation.",
  // layout
  QApp: "Application root container.",
  QHeader: "Top bar — fixed, translucent, top safe area.",
  QFooter: "Bottom bar — fixed, reveal, bottom safe area.",
  QPage: "Content area — `virtual` prop for virtual scroll.",
  QContainer: "Centered max-width container.",
  QToolbar: "Horizontal action bar.",
  QSpace: "Flexible spacer (pushes elements in flex layouts).",
  QSplitter: "Resizable layout — horizontal/vertical, limits.",
  QScrollArea: "Scrollable area with customizable scrollbar.",
  QVirtualScroll: "Virtualized list (windowed rendering) — measured heights.",
  QSidebar: "Side panel — side, overlay, breakpoint, v-model.",
  QSidebarContent: "Central scrollable area of the sidebar.",
  QSidebarFooter: "Bottom area of the sidebar.",
  QSidebarHeader: "Top area of the sidebar.",
  QSidebarMenu: "Sidebar navigation list.",
  QSidebarMenuButton: "Sidebar menu button (link wrapper).",
  QSidebarMenuItem: "Sidebar menu item.",
  QSidebarTrigger: "Sidebar toggle button.",
  QSafeArea: "Applies the requested safe-area insets to its sides.",
  QBackHeader: "Back bar — fixed, translucent, top safe area.",
  // navigation
  QTabs: "Tabs — align, active-color, animated indicator.",
  QTab: "Single tab item — icon, label, alert badge.",
  QAccordion: "Accordion — single/multiple, collapsible.",
  QAccordionContent: "Animated collapsible content of an accordion item.",
  QAccordionItem: "Accordion item — provides value + uid to children.",
  QAccordionTrigger: "Accordion opening button.",
  QCollapse: "Collapsible panel (QExpansionItem pattern).",
  QCarousel: "Embla-based carousel — orientation, plugins.",
  QCarouselContent: "Scrollable viewport + flex track of the carousel.",
  QCarouselItem: "Carousel slide.",
  QCarouselNav: "Carousel navigation (prev/next, dots).",
  QFab: "Floating action button with expandable actions.",
  QFabAction: "Individual action of a QFab.",
  QNavMenu: "Navigation bar with dropdown menus.",
  QNavMenuContent: "Dropdown panel of a navigation menu.",
  QNavMenuItem: "Navigation menu link.",
  QNavMenuTrigger: "Menu button with dropdown; content of the default slot is rendered inside.",
  QPagination: "Pagination — boundary/direction links, ellipses.",
  // chat
  QBubble: "Conversation bubble — variants, align.",
  QBubbleContent: "Bubble content body.",
  QBubbleGroup: "Group of consecutive bubbles from the same sender.",
  QBubbleReactions: "Reactions anchored to the bubble edge.",
  QMessageScroller: "Message log — anchored scrolling, streaming.",
  QMessageScrollerButton: "Floating back-to-live-edge button.",
  QMessageScrollerContent: "Log content.",
  QMessageScrollerItem: "Transcript row.",
  QMessageScrollerProvider: "Owns the scroll state.",
  QMessageScrollerViewport: "Native scrollable area.",
  // core
  QConfigProvider: "Theming — colors, componentProps (default props), radius.",
  QIcon: "Lucide icon (component).",
}

/** Live examples (no v-model: MDC has no reactive state) — valid component markup. */
const LIVE: Record<string, string> = {
  QApp: `<q-app class="not-prose rounded-sm border border-dashed p-4">
  <q-header style="background:white" class="text-sm font-semibold">Header</q-header>
  <q-page>Page content</q-page>
  <q-footer style="background:white" class="text-sm">Footer</q-footer>
</q-app>`,
  QHeader: `<q-header style="background:white" class="not-prose rounded-sm border border-dashed px-3 py-2 text-sm font-semibold">
  Top bar (top/left/right safe areas)
</q-header>`,
  QFooter: `<q-footer style="background:white" class="not-prose rounded-sm border border-dashed px-3 py-2 text-sm">
  Bottom bar (bottom safe area)
</q-footer>`,
  QPage: `<q-page class="not-prose rounded-sm border border-dashed p-4 text-sm">
  Content area (flex: 1 1 auto)
</q-page>`,
  QContainer: `<q-container class="not-prose rounded-sm border border-dashed p-4 text-sm">
  Centered max-width container
</q-container>`,
  QToolbar: `<q-toolbar class="not-prose rounded-sm border border-dashed px-3 text-sm font-semibold">
  <q-btn flat dense label="Back" />
  <q-space />
  <q-btn color="primary" dense label="Action" />
</q-toolbar>`,
  QSpace: `<div class="flex items-center gap-3 not-prose">
  <span>Left</span><q-space /><span>Right</span>
</div>`,
  QSafeArea: `<q-safe-area top bottom class="not-prose rounded-sm border border-dashed p-4 text-sm">
  Applies the requested insets
</q-safe-area>`,
  QBackHeader: `<q-back-header title="Details" class="not-prose" />`,
  QBtn: `<div class="flex flex-wrap items-center gap-3">
  <q-btn color="primary" label="Primary" />
  <q-btn color="secondary" flat label="Flat" />
  <q-btn color="negative" outline label="Outline" />
  <q-btn color="accent" radius="lg" label="Rounded" />
  <q-btn color="info" unelevated label="No shadow" />
</div>`,
  QBtnGroup: `<q-btn-group unelevated outline>
  <q-btn label="One" />
  <q-btn label="Two" />
  <q-btn label="Three" />
</q-btn-group>`,
  QInput: `<div class="grid gap-4">
  <q-input label="Email" outlined stack-label placeholder="you@example.com" />
  <q-input label="Search" filled dense stack-label />
</div>`,
  QInputPassword: `<q-input-password label="Password" outlined stack-label hint="Tap the eye to reveal" />`,
  QSelect: `<q-select
  :options="[{ label: 'Apple', value: 'apple' }, { label: 'Pear', value: 'pear' }, { label: 'Banana', value: 'banana' }]"
  label="Fruit"
  outlined
  stack-label
/>`,
  QAutocomplete: `<q-autocomplete
  :options="[{ label: 'Red', value: 'red' }, { label: 'Green', value: 'green' }, { label: 'Blue', value: 'blue' }]"
  label="Color"
  outlined
  stack-label
/>`,
  QCheckbox: `<div class="grid gap-3">
  <q-checkbox label="Option A" color="secondary" />
  <q-checkbox label="Option B" color="positive" />
</div>`,
  QRadio: `<div class="grid gap-3">
  <q-radio label="Option A" val="a" color="secondary" />
  <q-radio label="Option B" val="b" color="secondary" />
</div>`,
  QSlider: `<q-slider :min="0" :max="100" label markers class="pt-8" />`,
  QRating: `<q-rating :max="5" color="warning" size="lg" />`,
  QImagePicker: `<q-image-picker label="Photos" multiple />`,
  QFilePicker: `<q-file-picker label="Attachments" multiple />`,
  QAvatar: `<div class="flex items-center gap-4">
  <q-avatar src="https://i.pravatar.cc/96" alt="Avatar" />
  <q-avatar color="primary" text-color="white" :size="40">JD</q-avatar>
</div>`,
  QBadge: `<div class="flex flex-wrap items-center gap-3">
  <q-badge label="3" color="negative" />
  <q-badge label="New" color="primary" />
  <q-badge label="Draft" color="grey" outline />
</div>`,
  QChip: `<div class="flex flex-wrap items-center gap-3">
  <q-chip label="Chip" color="primary" />
  <q-chip label="Removable" color="secondary" removable />
  <q-chip label="Outline" outline />
</div>`,
  QCard: `<q-card class="max-w-sm" radius="md">
  <q-card-content>
    <p class="m-0 font-semibold">Card</p>
    <p class="m-0 text-sm opacity-70">Card content with rounded corners.</p>
  </q-card-content>
  <q-card-actions align="right">
    <q-btn flat label="Cancel" />
    <q-btn color="primary" label="OK" />
  </q-card-actions>
</q-card>`,
  QCardContent: `<q-card><q-card-content>Simple content</q-card-content></q-card>`,
  QCardActions: `<q-card><q-card-content>Aligned actions</q-card-content><q-card-actions align="right"><q-btn color="primary" label="OK" /></q-card-actions></q-card>`,
  QImg: `<q-img src="https://picsum.photos/400/200" ratio="16/9" class="max-w-md" alt="Example" />`,
  QList: `<q-list bordered separator class="max-w-sm">
  <q-item><q-item-section>Apple</q-item-section></q-item>
  <q-item><q-item-section>Pear</q-item-section></q-item>
  <q-item><q-item-section>Banana</q-item-section></q-item>
</q-list>`,
  QItem: `<q-list bordered class="max-w-sm">
  <q-item clickable><q-item-section>Clickable item</q-item-section></q-item>
  <q-item active><q-item-section>Active item</q-item-section></q-item>
</q-list>`,
  QItemSection: `<q-list class="max-w-sm">
  <q-item>
    <q-item-section avatar><q-avatar color="primary" text-color="white">A</q-avatar></q-item-section>
    <q-item-section>Title</q-item-section>
    <q-item-section side>12:00</q-item-section>
  </q-item>
</q-list>`,
  QSeparator: `<div><span>Before</span><q-separator spaced /><span>After</span></div>`,
  QSkeleton: `<div class="grid gap-3">
  <q-skeleton type="QBtn" width="120px" />
  <q-skeleton type="QInput" />
  <q-skeleton type="QAvatar" />
</div>`,
  QLinearProgress: `<div class="grid gap-4">
  <q-linear-progress :value="0.7" color="primary" />
  <q-linear-progress :value="0.45" color="positive" stripe />
</div>`,
  QCircularProgress: `<div class="flex items-center gap-6">
  <q-circular-progress :value="0.7" size="56px" color="primary" show-value />
  <q-circular-progress :value="0.45" size="56px" color="warning" />
</div>`,
  QInnerLoading: `<div class="relative rounded-sm border border-dashed p-10">
  <q-inner-loading showing label="Loading…" color="primary" />
</div>`,
  QTooltip: `<q-tooltip>Tooltip on hover</q-tooltip>`,
  QCollapse: `<q-collapse label="Details" default-opened class="max-w-sm">
  <p class="m-0 text-sm">Collapsible content with animation.</p>
</q-collapse>`,
}

/** Escapes a value for a YAML double-quoted string. */
function yamlQuote(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
}

function kebab(name: string) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/^Q/, "q-")
    .toLowerCase()
}

const noQ = (name: string) => name.replace(/^Q/, "")

/** Exemple d'un composant : live si dispo, sinon exemple de groupe, sinon tag nu. */
function exampleBlock(name: string): { kind: "live" | "code"; content: string } {
  if (LIVE[name]) return { kind: "live", content: LIVE[name] }
  const groupExample = Object.values(GROUP_EXAMPLES).find((g) => g[name])
  if (groupExample?.[name]) return { kind: "code", content: groupExample[name] }
  return { kind: "code", content: `<${kebab(name)} />` }
}

function buildPage(page: { name: string; components: string[] }) {
  const body: string[] = []
  page.components.forEach((comp, i) => {
    const heading = i === 0 ? "Example" : noQ(comp)
    body.push(`## ${heading}`, "")
    const ex = exampleBlock(comp)
    if (ex.kind === "live") {
      const inner = ex.content
        .trim()
        .split("\n")
        .map((l) => `    ${l}`)
        .join("\n")
      body.push("::prose-show-case")
      body.push("#default")
      body.push(inner)
      body.push("#code")
      body.push("  ```vue")
      body.push(ex.content.trim().split("\n").map((l) => `  ${l}`).join("\n"))
      body.push("  ```")
      body.push("::", "")
    } else {
      body.push("```vue")
      body.push(ex.content.trim())
      body.push("```", "")
    }
  })
  return body.join("\n")
}

async function main() {
  const files = (await readdir(COMPONENTS_DIR)).filter((f) => f.endsWith(".vue"))
  const allComponents = files.map((f) => f.replace(/\.vue$/, ""))

  // Nettoyage : supprime les anciennes pages générées (NN-Name.md)
  for (const old of (await readdir(OUT_DIR).catch(() => []))) {
    if (/^\d{2}-[A-Z].*\.md$/.test(old)) await rm(join(OUT_DIR, old))
  }
  await mkdir(OUT_DIR, { recursive: true })

  // Pages : familles (groupes) + composants autonomes
  const grouped = new Set(Object.values(GROUPS).flat())
  const pages: { name: string; components: string[] }[] = []
  for (const [name, comps] of Object.entries(GROUPS)) {
    pages.push({ name, components: comps })
  }
  for (const comp of allComponents) {
    if (!grouped.has(comp)) pages.push({ name: noQ(comp), components: [comp] })
  }
  pages.sort((a, b) => a.name.localeCompare(b.name))

  let count = 0
  for (const [index, page] of pages.entries()) {
    const num = String(index + 1).padStart(2, "0")
    const main = page.components[0]
    const parts = page.components.slice(1)
    const description = `${DESCRIPTIONS[main] ?? `DanxUI ${main} component.`}${
      parts.length ? ` Parts: ${parts.map(noQ).join(", ")}.` : ""
    }`
    const icon = ICONS[main] ?? "lucide:box"

    const frontmatter: string[] = []
    frontmatter.push("---")
    frontmatter.push(`title: ${page.name}`)
    frontmatter.push(`description: ${yamlQuote(description)}`)
    frontmatter.push("navigation:")
    frontmatter.push(`  icon: ${icon}`)
    frontmatter.push("componentApi:")
    frontmatter.push("  heading: API")
    frontmatter.push("  components:")
    for (const comp of page.components) {
      frontmatter.push(`    - path: ../packages/ui/components/${comp}.vue`)
      frontmatter.push(`      title: ${noQ(comp)}`)
    }
    frontmatter.push("---")

    const body = buildPage(page)
    await writeFile(join(OUT_DIR, `${num}-${page.name}.md`), frontmatter.join("\n") + "\n\n" + body + "\n")
    count++
  }

  // Configuration du dossier (Nuxt Content v3) — titre + icône du groupe
  await writeFile(
    join(OUT_DIR, ".navigation.yml"),
    "title: Components\nnavigation:\n  icon: lucide:boxes\n",
  )

  console.log(`✓ ${count} component pages generated in ${OUT_DIR}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
